### ISSUE TITLE
Leaked credentials

### ISSUE THREAD

**Issue by Rapptz** [GodPepe7/asb-auto-subs#2]
Hello.

I'm the creator of jimaku, thanks for using the API and I'm glad that you're making cool stuff with it.

Just a heads up, but in this line of code: https://github.com/GodPepe7/asb-auto-subs/blob/6cd6489472d0c795b3514c030495dfbb959b1385/src/background.ts#L130 you're leaking your API key for jimaku.cc. I've gone ahead and revoked it for you. It's best practice to not leak these tokens, since they can be used (somewhat) maliciously to upload files with your account. The API is *mostly* read-heavy so it's not a big issue, but in the interest of security it's best to not hardcode credentials within source code. Rather, read the API key from some type of configuration file.

Good luck with your tool!

**Comment by GodPepe7** [comment]
Thanks for the hint. I changed it with 1ad45a0d33e3fe6c4c87d17f2202310416028458 to make it a user input instead.
