### ISSUE TITLE
Idea/Fix - Avoid grabbing zip files unless it's a last resort

### ISSUE THREAD

**Issue by EliCodesForFun** [GodPepe7/asb-auto-subs#4]
For this example here:
https://jimaku.cc/entry/589

When downloading the subs for Air episode 1, the add-on went for:
AIR 2005 [01-06].SUP.7z
instead of finding the individual files here.
It would be good if this test case could be used to improve the effectiveness of this great add-on.

🥰

**Comment by GodPepe7** [comment]
Hi, I'm glad you like the extension. 
The extension should avoid grabbing zip, rar and 7z files now with b6460784fb6438492b1de4d84a20f56d8105e490.
It's in the latest release, so you can go ahead and try it
